In [1]:
import numpy as np

# 수치미분 함수

def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

# sigmoid 함수

def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [2]:
class LogicGate:
        
    def __init__(self, gate_name, xdata, tdata):
        
        self.name = gate_name
        
        # 입력 데이터, 정답 데이터 초기화
        self.__xdata = xdata.reshape(4,2)  # 4개의 입력데이터 x1, x2 에 대하여 batch 처리 행렬
        self.__tdata = tdata.reshape(4,1)  # 4개의 입력데이터 x1, x2 에 대한 각각의 계산 값 행렬
        
        # 2층 hidden layer unit : 6개 가정,  가중치 W2, 바이어스 b2 초기화
        self.__W2 = np.random.rand(2,6)  # weight, 2 X 6 matrix
        self.__b2 = np.random.rand(6)
        
        # 3층 output layer unit : 1 개 , 가중치 W3, 바이어스 b3 초기화
        self.__W3 = np.random.rand(6,1)
        self.__b3 = np.random.rand(1)
                        
        # 학습률 learning rate 초기화
        self.__learning_rate = 1e-2
    
        print(self.name + " object is created")
            
    def feed_forward(self):        # feed forward 를 통하여 손실함수(cross-entropy) 값 계산
        
        delta = 1e-7    # log 무한대 발산 방지
    
        z2 = np.dot(self.__xdata, self.__W2) + self.__b2  # 은닉층의 선형회귀 값
        a2 = sigmoid(z2)                                  # 은닉층의 출력
        
        z3 = np.dot(a2, self.__W3) + self.__b3            # 출력층의 선형회귀 값
        y = a3 = sigmoid(z3)                              # 출력층의 출력
    
        # cross-entropy 
        return  -np.sum( self.__tdata*np.log(y + delta) + (1-self.__tdata)*np.log((1 - y)+delta ) )    
    
    def loss_val(self):          # 외부 출력을 위한 손실함수(cross-entropy) 값 계산 
        
        delta = 1e-7    # log 무한대 발산 방지
    
        z2 = np.dot(self.__xdata, self.__W2) + self.__b2  # 은닉층의 선형회귀 값
        a2 = sigmoid(z2)                                  # 은닉층의 출력
        
        z3 = np.dot(a2, self.__W3) + self.__b3            # 출력층의 선형회귀 값
        y = a3 = sigmoid(z3)                              # 출력층의 출력
    
        # cross-entropy 
        return  -np.sum( self.__tdata*np.log(y + delta) + (1-self.__tdata)*np.log((1 - y)+delta ) )
    
    
    # 수치미분을 이용하여 손실함수가 최소가 될때 까지 학습하는 함수
    def train(self):
        
        f = lambda x : self.feed_forward()
        
        print("Initial loss value = ", self.loss_val())
        
        for step in  range(10001):
            
            self.__W2 -= self.__learning_rate * numerical_derivative(f, self.__W2)
    
            self.__b2 -= self.__learning_rate * numerical_derivative(f, self.__b2)
        
            self.__W3 -= self.__learning_rate * numerical_derivative(f, self.__W3)
    
            self.__b3 -= self.__learning_rate * numerical_derivative(f, self.__b3)
    
            if (step % 400 == 0):
                print("step = ", step, "  , loss value = ", self.loss_val())
                
    
    # query, 즉 미래 값 예측 함수
    def predict(self, xdata):
        
        z2 = np.dot(xdata, self.__W2) + self.__b2         # 은닉층의 선형회귀 값
        a2 = sigmoid(z2)                                  # 은닉층의 출력
        
        z3 = np.dot(a2, self.__W3) + self.__b3            # 출력층의 선형회귀 값
        y = a3 = sigmoid(z3)                              # 출력층의 출력
    
        if y > 0.5:
            result = 1  # True
        else:
            result = 0  # False
    
        return y, result

In [3]:
# AND Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 0, 0, 1])

and_obj = LogicGate("AND", xdata, tdata)

and_obj.train()

AND object is created
Initial loss value =  7.498983718103677
step =  0   , loss value =  7.243814636629539
step =  400   , loss value =  2.190050966429056
step =  800   , loss value =  1.988075399400972
step =  1200   , loss value =  1.6731438143084434
step =  1600   , loss value =  1.2923686574161604
step =  2000   , loss value =  0.9647908101451933
step =  2400   , loss value =  0.710076713125629
step =  2800   , loss value =  0.5237935430131448
step =  3200   , loss value =  0.39341499949518693
step =  3600   , loss value =  0.3034368782095729
step =  4000   , loss value =  0.24076113551310577
step =  4400   , loss value =  0.19612397003689375
step =  4800   , loss value =  0.16346524327852244
step =  5200   , loss value =  0.13891639036027614
step =  5600   , loss value =  0.11999752998813416
step =  6000   , loss value =  0.1050900826478979
step =  6400   , loss value =  0.09311247504335252
step =  6800   , loss value =  0.08332384989045247
step =  7200   , loss value =  0.075204

In [4]:
# AND Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(and_obj.predict(data))

(array([0.00010261]), 0)
(array([0.01167075]), 0)
(array([0.01100847]), 0)
(array([0.97985837]), 1)


In [5]:
# OR Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 1, 1, 1])

or_obj = LogicGate("OR", xdata, tdata)

or_obj.train()

OR object is created
Initial loss value =  2.3610704831515408
step =  0   , loss value =  2.3503540923719064
step =  400   , loss value =  1.9956716253628959
step =  800   , loss value =  1.828482375471356
step =  1200   , loss value =  1.569679456647357
step =  1600   , loss value =  1.2336374081745138
step =  2000   , loss value =  0.902565710667908
step =  2400   , loss value =  0.6436352154846339
step =  2800   , loss value =  0.4649479522146127
step =  3200   , loss value =  0.3464381911600241
step =  3600   , loss value =  0.2672008880618061
step =  4000   , loss value =  0.21272278672673636
step =  4400   , loss value =  0.1740100349256504
step =  4800   , loss value =  0.1456070455806299
step =  5200   , loss value =  0.1241595433675118
step =  5600   , loss value =  0.10755062916677754
step =  6000   , loss value =  0.09440427032842576
step =  6400   , loss value =  0.08379957040868048
step =  6800   , loss value =  0.07510320632900928
step =  7200   , loss value =  0.06786865

In [6]:
# OR Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(or_obj.predict(data))

(array([0.02329714]), 0)
(array([0.99243182]), 1)
(array([0.99221888]), 1)
(array([0.99976783]), 1)


In [7]:
# NAND Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([1, 1, 1, 0])

nand_obj = LogicGate("NAND", xdata, tdata)

nand_obj.train()

NAND object is created
Initial loss value =  3.80345936302085
step =  0   , loss value =  3.766157802435016
step =  400   , loss value =  2.189056281772771
step =  800   , loss value =  1.981614769539415
step =  1200   , loss value =  1.6783977437378188
step =  1600   , loss value =  1.3260787913939334
step =  2000   , loss value =  0.9974196485111462
step =  2400   , loss value =  0.7392384014347331
step =  2800   , loss value =  0.5530831122062214
step =  3200   , loss value =  0.4225898872914278
step =  3600   , loss value =  0.3310724532420182
step =  4000   , loss value =  0.2659023643010384
step =  4400   , loss value =  0.2184654472499576
step =  4800   , loss value =  0.18310591133091758
step =  5200   , loss value =  0.15613263914263353
step =  5600   , loss value =  0.13511227556316127
step =  6000   , loss value =  0.11841220215758116
step =  6400   , loss value =  0.10491439073542813
step =  6800   , loss value =  0.09383696128574848
step =  7200   , loss value =  0.0846218

In [8]:
# NAND Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(nand_obj.predict(data))

(array([0.9999478]), 1)
(array([0.98819001]), 1)
(array([0.98896886]), 1)
(array([0.02490962]), 0)


In [9]:
# XOR Gate 객체 생성

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 1, 1, 0])


xor_obj = LogicGate("XOR", xdata, tdata)

xor_obj.train()

XOR object is created
Initial loss value =  3.3487246215211073
step =  0   , loss value =  3.3114492475044726
step =  400   , loss value =  2.7712040965500786
step =  800   , loss value =  2.769779958621593
step =  1200   , loss value =  2.7681646434615335
step =  1600   , loss value =  2.7661956534630407
step =  2000   , loss value =  2.763647850368869
step =  2400   , loss value =  2.760189405718283
step =  2800   , loss value =  2.7553168758322966
step =  3200   , loss value =  2.7482643241064233
step =  3600   , loss value =  2.737888928785919
step =  4000   , loss value =  2.7225470150316973
step =  4400   , loss value =  2.699976705830164
step =  4800   , loss value =  2.667198050697841
step =  5200   , loss value =  2.620535079628988
step =  5600   , loss value =  2.5562145677303336
step =  6000   , loss value =  2.4721826362401473
step =  6400   , loss value =  2.370406132224458
step =  6800   , loss value =  2.256720651087708
step =  7200   , loss value =  2.137213821403046
st

In [10]:
test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(xor_obj.predict(data))

(array([0.09117056]), 0)
(array([0.78956313]), 1)
(array([0.71676602]), 1)
(array([0.37000683]), 0)
